import uuid
from django.db import models
from django.conf import settings


class Plan(models.Model):
    PLAN_TYPES = [
        ('token', 'Token Based'),
        ('basic', 'Basic'),
        ('premium', 'Premium'),
        ('vip', 'VIP'),
    ]

    name = models.CharField(max_length=100)
    plan_type = models.CharField(max_length=20, choices=PLAN_TYPES)
    description = models.TextField(blank=True)
    price_npr = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_usd = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ai_tokens = models.PositiveIntegerField(default=0)
    duration_days = models.PositiveIntegerField(default=30)
    features = models.JSONField(default=list)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'subscription_plans'

    def __str__(self):
        return f"{self.name} ({self.plan_type})"


class Payment(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
        ('refunded', 'Refunded'),
    ]
    GATEWAY_CHOICES = [
        ('khalti', 'Khalti'),
        ('esewa', 'eSewa'),
        ('stripe', 'Stripe'),
        ('fonepay', 'FonePay'),
    ]
    CURRENCY_CHOICES = [('NPR', 'NPR'), ('USD', 'USD')]

    # Unique transaction ID generated by us
    transaction_uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='payments')
    plan = models.ForeignKey(Plan, on_delete=models.PROTECT, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='NPR')
    gateway = models.CharField(max_length=20, choices=GATEWAY_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    description = models.CharField(max_length=255, blank=True)

    # Gateway-specific transaction references
    gateway_transaction_id = models.CharField(max_length=255, blank=True)  # pidx (Khalti), refId (eSewa)
    gateway_response = models.JSONField(default=dict, blank=True)          # full response stored

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'payments'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.email} | {self.gateway} | {self.amount} {self.currency} | {self.status}"


class UserSubscription(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('expired', 'Expired'),
        ('cancelled', 'Cancelled'),
        ('pending', 'Pending'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='subscriptions')
    plan = models.ForeignKey(Plan, on_delete=models.PROTECT)
    payment = models.OneToOneField(Payment, on_delete=models.SET_NULL,
                                   null=True, blank=True, related_name='subscription')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    started_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'user_subscriptions'

    def __str__(self):
        return f"{self.user.email} - {self.plan.name} ({self.status})"
