# Generated by Django 6.0.4 on 2026-04-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('astrologer', 'Astrologer')], default='user', max_length=20),
        ),
    ]
