# Generated by Django 6.0.4 on 2026-04-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astrologer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('specializations', models.JSONField(default=list)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(default=list)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='astrologers/')),
                ('rate_per_min_npr', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('rate_per_min_usd', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('is_available', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('total_consultations', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'astrologers',
            },
        ),
        migrations.CreateModel(
            name='AstrologerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'astrologer_availability',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('chat', 'Chat'), ('video', 'Video Call'), ('phone', 'Phone Call')], default='chat', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'consultations',
            },
        ),
    ]
