# Generated by Django 6.0.4 on 2026-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologer',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='astrologer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='astrologer',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
