# Generated by Django 6.0.4 on 2026-04-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologers', '0003_astrologer_profile_complete_alter_astrologer_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
    ]
