# Generated by Django 6.0.4 on 2026-04-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_data', models.JSONField(default=dict)),
                ('ascendant', models.CharField(blank=True, max_length=50)),
                ('moon_sign', models.CharField(blank=True, max_length=50)),
                ('sun_sign', models.CharField(blank=True, max_length=50)),
                ('nakshatra', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'birth_charts',
            },
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_sign', models.CharField(choices=[('aries', 'Aries'), ('taurus', 'Taurus'), ('gemini', 'Gemini'), ('cancer', 'Cancer'), ('leo', 'Leo'), ('virgo', 'Virgo'), ('libra', 'Libra'), ('scorpio', 'Scorpio'), ('sagittarius', 'Sagittarius'), ('capricorn', 'Capricorn'), ('aquarius', 'Aquarius'), ('pisces', 'Pisces')], max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('love', models.TextField(blank=True)),
                ('career', models.TextField(blank=True)),
                ('health', models.TextField(blank=True)),
                ('finance', models.TextField(blank=True)),
                ('lucky_number', models.PositiveIntegerField(blank=True, null=True)),
                ('lucky_color', models.CharField(blank=True, max_length=50)),
                ('compatibility', models.CharField(blank=True, max_length=50)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'horoscopes',
            },
        ),
        migrations.CreateModel(
            name='KundaliMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_dob', models.DateField()),
                ('partner_tob', models.TimeField(blank=True, null=True)),
                ('partner_pob', models.CharField(blank=True, max_length=200)),
                ('match_score', models.PositiveSmallIntegerField(default=0)),
                ('match_details', models.JSONField(default=dict)),
                ('ai_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kundali_matches',
            },
        ),
        migrations.CreateModel(
            name='PlanetaryTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(max_length=50)),
                ('from_sign', models.CharField(max_length=50)),
                ('to_sign', models.CharField(max_length=50)),
                ('transit_date', models.DateField()),
                ('description', models.TextField()),
                ('impact', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'planetary_transits',
            },
        ),
    ]
